ALTER TYPE "public"."city" ADD VALUE 'Alexandria';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Giza';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'ShubraElKheima';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'PortSaid';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Suez';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Luxor';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Mansoura';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'ElMahallaElKubra';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Tanta';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Asyut';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Ismailia';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Faiyum';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Zagazig';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Damietta';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Aswan';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Minya';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Damanhur';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'BeniSuef';--> statement-breakpoint
ALTER TYPE "public"."city" ADD VALUE 'Hurghada';--> statement-breakpoint
ALTER TABLE "addresses" ADD COLUMN "floorNumber" integer NOT NULL;