// ~/components/shopping/productData.ts
import { ProductCategory } from '~/db/schema'

export interface Product {
  id: number
  name: string
  price: number
  image: string
  description: string
  category: ProductCategory
}

export const products: Product[] = [
  // Kitchen Supplies (1-20)
  {
    id: 1,
    name: 'Professional Stand Mixer',
    price: 299.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/4109850/pexels-photo-4109850.jpeg',
    description: 'Professional-grade stand mixer with multiple attachments and speed settings.',
  },
  {
    id: 2,
    name: 'Smart Coffee Maker',
    price: 149.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/2638019/pexels-photo-2638019.jpeg',
    description: 'Programmable coffee maker with built-in grinder and timer.',
  },
  {
    id: 3,
    name: 'Premium Cookware Set',
    price: 399.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/3214161/pexels-photo-3214161.jpeg',
    description: 'Complete set of non-stick cookware with premium coating.',
  },
  {
    id: 4,
    name: 'Digital Food Scale',
    price: 29.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/4226896/pexels-photo-4226896.jpeg',
    description: 'Precise digital kitchen scale with multiple measurement units.',
  },
  {
    id: 5,
    name: 'Air Fryer Pro',
    price: 179.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/6605302/pexels-photo-6605302.jpeg',
    description: 'Large capacity air fryer with digital controls and presets.',
  },
  {
    id: 6,
    name: 'Chef Knife Set',
    price: 199.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/4226891/pexels-photo-4226891.jpeg',
    description: 'Professional knife set with storage block and sharpener.',
  },
  {
    id: 7,
    name: 'Food Processor Plus',
    price: 159.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/3794149/pexels-photo-3794149.jpeg',
    description: 'Versatile food processor with multiple attachments.',
  },
  {
    id: 8,
    name: 'Electric Pressure Cooker',
    price: 129.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/4109832/pexels-photo-4109832.jpeg',
    description: 'Multi-functional pressure cooker with 12 preset programs.',
  },
  {
    id: 9,
    name: 'Professional Blender',
    price: 249.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/3735188/pexels-photo-3735188.jpeg',
    description: 'High-powered blender for smoothies and food processing.',
  },
  {
    id: 10,
    name: 'Rice Cooker Deluxe',
    price: 89.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/4109856/pexels-photo-4109856.jpeg',
    description: 'Advanced rice cooker with multiple grain settings.',
  },
  {
    id: 11,
    name: 'Sous Vide Cooker',
    price: 199.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/3735186/pexels-photo-3735186.jpeg',
    description: 'Precision sous vide cooker with WiFi connectivity.',
  },
  {
    id: 12,
    name: 'Electric Wine Opener',
    price: 39.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/1479314/pexels-photo-1479314.jpeg',
    description: 'Rechargeable electric wine opener with foil cutter.',
  },
  {
    id: 13,
    name: 'Cold Press Juicer',
    price: 159.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/616833/pexels-photo-616833.jpeg',
    description: 'Slow masticating juicer for maximum nutrient retention.',
  },
  {
    id: 14,
    name: 'Pizza Stone Set',
    price: 49.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/905847/pexels-photo-905847.jpeg',
    description: 'Professional pizza stone with peel and cutter.',
  },
  {
    id: 15,
    name: 'Spice Rack Organizer',
    price: 34.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/4226892/pexels-photo-4226892.jpeg',
    description: 'Three-tier spice rack with 24 labeled jars.',
  },
  {
    id: 16,
    name: 'Electric Kettle',
    price: 79.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/4226895/pexels-photo-4226895.jpeg',
    description: 'Temperature control kettle with keep-warm function.',
  },
  {
    id: 17,
    name: 'Food Dehydrator',
    price: 119.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/4226897/pexels-photo-4226897.jpeg',
    description: '6-tray food dehydrator with digital controls.',
  },
  {
    id: 18,
    name: 'Ice Cream Maker',
    price: 89.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/4226898/pexels-photo-4226898.jpeg',
    description: 'Automatic ice cream maker with gelato setting.',
  },
  {
    id: 19,
    name: 'Kitchen Island Cart',
    price: 199.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/4226899/pexels-photo-4226899.jpeg',
    description: 'Rolling kitchen island with storage and butcher block top.',
  },
  {
    id: 20,
    name: 'Vacuum Sealer',
    price: 79.99,
    category: 'kitchensupplies',
    image: 'https://images.pexels.com/photos/4226900/pexels-photo-4226900.jpeg',
    description: 'Food vacuum sealer with built-in bag cutter.',
  },

  // Bathroom Supplies (21-40)
  {
    id: 21,
    name: 'Luxury Towel Set',
    price: 79.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/3771691/pexels-photo-3771691.jpeg',
    description: 'Premium cotton towel set including bath, hand, and face towels.',
  },
  {
    id: 22,
    name: 'Modern Bathroom Organizer',
    price: 49.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461521/pexels-photo-6461521.jpeg',
    description: 'Sleek bathroom organizer with multiple compartments.',
  },
  {
    id: 23,
    name: 'Smart Scale',
    price: 59.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/4046316/pexels-photo-4046316.jpeg',
    description: 'Digital bathroom scale with body composition analysis.',
  },
  {
    id: 24,
    name: 'LED Mirror',
    price: 129.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6585750/pexels-photo-6585750.jpeg',
    description: 'Illuminated bathroom mirror with touch controls.',
  },
  {
    id: 25,
    name: 'Shower Caddy Deluxe',
    price: 34.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461567/pexels-photo-6461567.jpeg',
    description: 'Rustproof shower organizer with adjustable shelves.',
  },
  {
    id: 26,
    name: 'Bath Mat Set',
    price: 39.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6207818/pexels-photo-6207818.jpeg',
    description: 'Non-slip bath mat set with matching toilet cover.',
  },
  {
    id: 27,
    name: 'Soap Dispenser Set',
    price: 29.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461559/pexels-photo-6461559.jpeg',
    description: 'Modern soap and lotion dispenser set.',
  },
  {
    id: 28,
    name: 'Heated Towel Rack',
    price: 149.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461558/pexels-photo-6461558.jpeg',
    description: 'Wall-mounted heated towel rack with timer.',
  },
  {
    id: 29,
    name: 'Rainfall Shower Head',
    price: 89.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461557/pexels-photo-6461557.jpeg',
    description: 'Large rainfall shower head with multiple spray patterns.',
  },
  {
    id: 30,
    name: 'Toilet Paper Storage',
    price: 44.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461556/pexels-photo-6461556.jpeg',
    description: 'Freestanding toilet paper storage with shelf.',
  },
  {
    id: 31,
    name: 'Makeup Organizer',
    price: 39.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461555/pexels-photo-6461555.jpeg',
    description: 'Rotating makeup organizer with adjustable shelves.',
  },
  {
    id: 32,
    name: 'Electric Toothbrush Set',
    price: 129.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461554/pexels-photo-6461554.jpeg',
    description: 'Smart electric toothbrush with UV sanitizer.',
  },
  {
    id: 33,
    name: 'Over-Toilet Storage',
    price: 69.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461553/pexels-photo-6461553.jpeg',
    description: 'Space-saving over-toilet storage cabinet.',
  },
  {
    id: 34,
    name: 'Shower Door Squeegee',
    price: 19.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461552/pexels-photo-6461552.jpeg',
    description: 'Professional shower door squeegee with holder.',
  },
  {
    id: 35,
    name: 'Bathroom Corner Shelf',
    price: 34.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461551/pexels-photo-6461551.jpeg',
    description: 'Tension pole corner shelf with adjustable height.',
  },
  {
    id: 36,
    name: 'Hair Tool Organizer',
    price: 29.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461550/pexels-photo-6461550.jpeg',
    description: 'Wall-mounted hair dryer and styling tool organizer.',
  },
  {
    id: 37,
    name: 'Shower Curtain Set',
    price: 44.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461549/pexels-photo-6461549.jpeg',
    description: 'Premium shower curtain with hooks and liner.',
  },
  {
    id: 38,
    name: 'Bath Pillow',
    price: 24.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461548/pexels-photo-6461548.jpeg',
    description: 'Spa bath pillow with suction cups.',
  },
  {
    id: 39,
    name: 'Toilet Brush Set',
    price: 29.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461547/pexels-photo-6461547.jpeg',
    description: 'Modern toilet brush with quick-dry holder.',
  },
  {
    id: 40,
    name: 'Bath Caddy',
    price: 49.99,
    category: 'bathroomsupplies',
    image: 'https://images.pexels.com/photos/6461546/pexels-photo-6461546.jpeg',
    description: 'Expandable bamboo bath caddy with wine holder.',
  },

  // Home Supplies (41-60)
  {
    id: 41,
    name: 'Robot Vacuum',
    price: 299.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/4087992/pexels-photo-4087992.jpeg',
    description: 'Smart robot vacuum with mapping technology.',
  },
  {
    id: 42,
    name: 'Air Purifier',
    price: 199.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/4149264/pexels-photo-4149264.jpeg',
    description: 'HEPA air purifier with air quality monitor.',
  },
  {
    id: 43,
    name: 'Storage Ottoman',
    price: 89.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/6207755/pexels-photo-6207755.jpeg',
    description: 'Multi-functional storage ottoman with tray top.',
  },
  {
    id: 44,
    name: 'Closet Organizer',
    price: 79.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/5706273/pexels-photo-5706273.jpeg',
    description: 'Expandable closet organization system.',
  },
  {
    id: 45,
    name: 'Smart LED Bulb Set',
    price: 49.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/1435075/pexels-photo-1435075.jpeg',
    description: 'Color-changing smart LED bulbs, pack of 4.',
  },
  {
    id: 46,
    name: 'Laundry Center',
    price: 159.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/5591581/pexels-photo-5591581.jpeg',
    description: 'Rolling laundry sorter with folding station.',
  },
  {
    id: 47,
    name: 'Shoe Storage Cabinet',
    price: 129.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/4482036/pexels-photo-4482036.jpeg',
    description: 'Modern shoe storage cabinet with doors.',
  },
  {
    id: 48,
    name: 'Dehumidifier',
    price: 179.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg',
    description: 'Energy-efficient dehumidifier with auto shut-off.',
  },
  {
    id: 49,
    name: 'Wall Clock',
    price: 39.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/1095550/pexels-photo-1095550.jpeg',
    description: 'Modern wall clock with silent movement.',
  },
  {
    id: 50,
    name: 'Bedding Set',
    price: 129.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg',
    description: 'Luxury bedding set with duvet cover and pillowcases.',
  },
  {
    id: 51,
    name: 'Picture Frame Set',
    price: 59.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/1090638/pexels-photo-1090638.jpeg',
    description: 'Gallery wall picture frame set, various sizes.',
  },
  {
    id: 52,
    name: 'Throw Blanket',
    price: 44.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/6032424/pexels-photo-6032424.jpeg',
    description: 'Plush throw blanket with decorative tassels.',
  },
  {
    id: 53,
    name: 'Desk Organizer',
    price: 34.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/6207816/pexels-photo-6207816.jpeg',
    description: 'Multi-compartment desk organizer with drawer.',
  },
  {
    id: 54,
    name: 'Window Curtains',
    price: 69.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/1743227/pexels-photo-1743227.jpeg',
    description: 'Blackout curtains with thermal insulation.',
  },
  {
    id: 55,
    name: 'Plant Stand Set',
    price: 49.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/6207837/pexels-photo-6207837.jpeg',
    description: 'Set of 3 modern plant stands, different heights.',
  },
  {
    id: 56,
    name: 'Drawer Organizers',
    price: 29.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/6207844/pexels-photo-6207844.jpeg',
    description: 'Adjustable drawer dividers and organizers.',
  },
  {
    id: 57,
    name: 'Door Mat Set',
    price: 39.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/6207858/pexels-photo-6207858.jpeg',
    description: 'Indoor and outdoor door mat set with brush cleaning.',
  },
  {
    id: 58,
    name: 'Decorative Pillows',
    price: 44.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/6207863/pexels-photo-6207863.jpeg',
    description: 'Set of 4 decorative throw pillows with covers.',
  },
  {
    id: 59,
    name: 'Magazine Rack',
    price: 34.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/6207869/pexels-photo-6207869.jpeg',
    description: 'Modern wall-mounted magazine and book rack.',
  },
  {
    id: 60,
    name: 'Storage Baskets',
    price: 39.99,
    category: 'homesupplies',
    image: 'https://images.pexels.com/photos/6207875/pexels-photo-6207875.jpeg',
    description: 'Set of 3 woven storage baskets with handles.',
  },
]
